### deleted lalitha173 environment
trigger:
- main

variables:
  artifactName: drop
  azureServiceConnection: 'Azure-Service-Connection'
  webAppName: 'lalitha173-hggvhvandndtc3an'

stages:

# ================= BUILD =================
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        jdkVersionOption: '1.17'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'target'
        artifact: $(artifactName)

# ================= TEST =================
- stage: Test
  displayName: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'

# ================= DEV DEPLOY =================
- stage: Dev
  displayName: Deploy to Dev
  dependsOn: Test
  jobs:
  - deployment: DevDeploy
    environment: Dev
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureServiceConnection)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/$(artifactName)/*.jar'

# ================= QA DEPLOY (Approval) =================
- stage: QA
  displayName: Deploy to QA
  dependsOn: Dev
  jobs:
  - deployment: QADeploy
    environment: QA   # Approval enabled here
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureServiceConnection)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/$(artifactName)/*.jar'

# ================= PROD DEPLOY (Approval + Rollback) =================
- stage: Prod
  displayName: Deploy to Prod
  dependsOn: QA
  jobs:
  - deployment: ProdDeploy
    environment: Prod   # Approval enabled here
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureServiceConnection)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/$(artifactName)/*.jar'
